### ISSUE TITLE
Fix issue with badges

### ISSUE THREAD

**Issue by miguelgfierro** [miguelgfierro/codebase#231]
Badges from shields.io continuously down

More info of the issue here https://github.com/badges/shields/issues/445

Option 1:
That's probably GitHub's rate limit on one server kicking in. I suggest using https://img.shields.io/badge/license-mit-blue.svg?style=flat-square instead. That will essentially instantaneously load.

Option 2:
Thats why I recommended reverse caching proxy (using nginx for example)
That way you can still use your domain https://shields.mydomain.io which is proxy to https://img.shields.io so when https://img.shields.io is not available you will still get cached results instead of hanging

**Comment by miguelgfierro** [comment]
to add ?style=flat-square  doesn't work

**Comment by miguelgfierro** [comment]
According to this issue page, https://github.com/badges/shields/issues/1568, there is no short time solution for the issue, they need more money to provide a better service. 

As of now, the alternative would be to host [my own server](https://github.com/badges/shields/blob/master/doc/self-hosting.md) of shield.io or to create a program that calls shield.io and if it's taking more than X seconds to resolve, then send a backup version

**Comment by kopax** [comment]
@miguelgfierro thanks for detailling this.

I would be interested if you could share your solution. I was about to start my own docker server and then I realised the default image available expect us to provide `GH_*` variables in a unsafe manner. 

If we could remove this and use caching, I believe this would be a perfect solution.

**Comment by miguelgfierro** [comment]
If I do this, I'll share it as opensource code
